In [120]:
import numpy as np
import pandas as pd
train_data = pd.read_csv("report.csv", delimiter=',')

In [121]:
train_data.head()

MIP      STDIP      EKIP       SIP         MC       STDC        EKC  \
0  96.203125  45.111729  0.773960  1.435801   2.346154  14.867269   9.468971   
1  80.640625  56.308821  1.481006  1.952136  27.807692  63.855448   2.179750   
2  96.281250  40.433769  0.518182  1.584537   2.040970  12.956545  10.757996   
3  80.140625  34.426265  1.697879  6.213364   7.822742  38.341936   5.048004   
4  80.523438  54.076185  1.390950  1.282292  66.311873  77.549955   0.870147   

           SC  TARGET  
0  112.136515       0  
1    3.354892       1  
2  155.213413       0  
3   24.802277       1  
4   -0.478376       1

In [122]:
train_data.MIP.mean()

88.46863511029412

In [132]:
X = train_data.drop('TARGET', axis=1)

In [133]:
y = train_data.TARGET

In [134]:
X.describe()

MIP       STDIP        EKIP         SIP          MC        STDC  \
count  204.000000  204.000000  204.000000  204.000000  204.000000  204.000000   
mean    88.468635   43.566916    0.993654    2.442137   21.946718   37.338799   
std      7.882884    6.954587    0.563630    2.223334   37.538892   24.936980   
min     77.492188   31.006264    0.190183   -0.632872    0.414716    8.425768   
25%     80.681641   38.993863    0.490087    0.780458    2.277592   16.088394   
50%     95.898438   42.794676    0.837797    1.727154    4.905936   26.995302   
75%     96.166016   46.936911    1.490166    3.900567   21.297868   54.272147   
max     96.414062   83.796909    2.503509   11.832445  170.805184   98.321744   

              EKC          SC  
count  204.000000  204.000000  
mean     6.482781   75.746693  
std      4.853043  102.876836  
min     -1.227876   -1.837085  
25%      2.496860    5.315555  
50%      6.250413   41.611636  
75%      9.561671  107.621517  
max     25.968793  733.935093

In [135]:
mip = []
for var in X.MIP :
    res = (var - 77.492188) / (96.414062 - 77.492188) 
    mip.append(res)
X.MIP = mip

In [136]:
X.MIP.mean()

0.5800930240997333

In [138]:
X.STDIP = (X.STDIP-31.006264)/(83.796909 - 31.006264)
X.EKIP = (X.EKIP -0.190183 )/(2.503509 -0.190183 )
X.SIP = (X.SIP + 0.632872)/(11.832445 +0.632872 )
X.MC = (X.MC -0.414716 )/(170.805184 -0.414716 )
X.STDC = (X.STDC -8.425768 )/(98.321744 - 8.425768)
X.EKC = (X.EKC + 1.227876 )/(25.968793 + -1.227876)
X.SC = (X.SC + 1.837085 )/(733.935093 + 1.837085 )

In [139]:
from sklearn.linear_model import LogisticRegression

In [140]:
reg = LogisticRegression(random_state=2019, solver='lbfgs')

In [141]:
reg.fit(X, y.values.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=2019, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [142]:
reg.predict_proba([[0.363, 0.178, 0.43, 0.292, 0.575, 0.872, 0.023, 0.161]])

array([[0.09356015, 0.90643985]])

In [143]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5, p=2)
neigh.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [144]:
neigh.predict([[0.363, 0.178, 0.43, 0.292, 0.575, 0.872, 0.023, 0.161]])

array([1])

In [145]:
neigh.kneighbors([[0.363, 0.178, 0.43, 0.292, 0.575, 0.872, 0.023, 0.161]])

(array([[0.24975002, 0.2669713 , 0.27648819, 0.30468442, 0.34516136]]),
 array([[ 93, 106, 168, 198, 158]]))