In [3]:
import numpy as np
import pandas as pd
train_data = pd.read_csv("report.csv", delimiter=',')

In [4]:
train_data.head()

MIP      STDIP      EKIP       SIP         MC       STDC        EKC  \
0  137.218750  45.390655  0.034985  0.134409   3.204013  17.177857   7.494588   
1   93.773438  41.883062  0.371402  1.291232   1.482441  12.959050  12.242911   
2   73.632812  35.461218  1.153607  4.161082   2.099498  13.057474  10.013591   
3   93.429688  39.883166  0.602060  1.518548   2.475753  14.146578   8.770640   
4  131.625000  44.111896  0.108905  0.239879  33.888796  70.398342   1.689460   

           SC  TARGET  
0   74.003104       0  
1  180.158844       0  
2  140.894151       0  
3  107.970173       0  
4    1.031847       0

In [5]:
X = train_data.drop('TARGET', axis=1)

In [6]:
y = train_data.TARGET

In [7]:
from sklearn.linear_model import LogisticRegression

In [10]:
reg = LogisticRegression(random_state=2019, solver='lbfgs')

In [11]:
reg.fit(X, y.values.ravel())

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=2019, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
reg.predict_proba([[0.363, 0.178, 0.43, 0.292, 0.575, 0.872, 0.023, 0.161]])

array([[0.16350154, 0.83649846]])

In [17]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5, p=2)
neigh.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [18]:
neigh.predict([[0.363, 0.178, 0.43, 0.292, 0.575, 0.872, 0.023, 0.161]])

array([1])

In [19]:
neigh.predict_proba([[0.363, 0.178, 0.43, 0.292, 0.575, 0.872, 0.023, 0.161]])

array([[0., 1.]])

In [20]:
neigh.kneighbors([[0.363, 0.178, 0.43, 0.292, 0.575, 0.872, 0.023, 0.161]])

(array([[64.39822259, 64.61885011, 66.12789191, 66.16941141, 66.31586379]]),
 array([[10326,  4668,  2046, 11867, 12751]]))