In [76]:
import pandas as pd
import numpy as np

In [111]:
data = pd.read_csv("model.csv", encoding = 'UTF-8', delimiter=',', index_col='id')

In [112]:
data

X   Y
id        
1   10  17
2   13  21
3   11  23
4   12  39
5   17  31
6    7  15
7   16  49
8    1   2
9    8  19
10   9  22

In [113]:
#отбираем данные для предикторов, удаляя два последних столбца, индекс не включается в данные.
X = data.drop(['Y'], axis=1)

In [114]:
#указываем столбец отклика
y = data['Y']

In [115]:
#подключаем модель линейной регрессии из библиотеки sklearn
from sklearn.linear_model import LinearRegression

In [116]:
#обучение модели
reg = LinearRegression().fit(X, y)

In [117]:
#предсказание
reg.predict([[9]])

array([20.47609148])

In [118]:
data

X   Y
id        
1   10  17
2   13  21
3   11  23
4   12  39
5   17  31
6    7  15
7   16  49
8    1   2
9    8  19
10   9  22

In [138]:
#предсказание для pначений из таблицы

#выбираем строку из таблицы
first = data.loc[1,:].to_frame().T

#отбираем данные для предикторов и выполняем предсказание с помощью модели
reg.predict(first.drop(columns=['Y'])) 

array([22.85031185])

In [120]:
reg.intercept_

-0.8918918918918841

In [121]:
reg.coef_

array([2.37422037])

In [122]:
data['X'].mean()

10.4

In [123]:
data['Y'].mean()

23.8

In [124]:
from sklearn.metrics import r2_score

In [153]:
y_pred=[]
for i in range(1,11):
    x = data.loc[i,:].to_frame().T
    p = reg.predict(x.drop(columns=['Y']))
    y_pred.append(p[0])

y_pred

[22.85031185031185,
 29.972972972972972,
 25.224532224532226,
 27.5987525987526,
 39.46985446985447,
 15.72765072765073,
 37.0956340956341,
 1.4823284823284895,
 18.101871101871104,
 20.47609147609148]

In [154]:
y = data['Y'].tolist()

In [155]:
r2_score(y, y_pred)

0.6989841885433534