In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("candy-data.csv", encoding = 'UTF-8', delimiter=',', index_col='competitorname')

In [6]:
train_data = data.drop(['Milky Way','Mr Good Bar'])

In [7]:
#отбираем данные для предикторов, удаляя два последних столбца, индекс не включается в данные.
X = pd.DataFrame(train_data.drop(['winpercent', 'Y'], axis=1))

In [8]:
#указываем столбец отклика
y = pd.DataFrame(train_data['winpercent'])

In [9]:
#подключаем модель линейной регрессии из библиотеки sklearn
from sklearn.linear_model import LinearRegression

In [10]:
#обучение модели
reg = LinearRegression().fit(X, y)

In [28]:
#выбираем строку из таблицы
milky = data.loc['Milky Way',:].to_frame().T
milky = milky.drop(['winpercent', 'Y'],axis=1)
milky

chocolate  fruity  caramel  peanutyalmondy  nougat  \
Milky Way        1.0     0.0      1.0             0.0     1.0   

           crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  
Milky Way               0.0   0.0  1.0       0.0         0.604         0.651

In [31]:
#отбираем данные для предикторов и выполняем предсказание с помощью модели
reg.predict(milky)

array([[55.54422446]])

In [33]:
goodbar = data.loc['Mr Good Bar',:].to_frame().T
goodbar = goodbar.drop(['winpercent', 'Y'],axis=1)
goodbar

chocolate  fruity  caramel  peanutyalmondy  nougat  \
Mr Good Bar        1.0     0.0      0.0             1.0     0.0   

             crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  
Mr Good Bar               0.0   0.0  1.0       0.0         0.313         0.918

In [34]:
#отбираем данные для предикторов и выполняем предсказание с помощью модели
reg.predict(goodbar)

array([[61.82432832]])

In [35]:
#предсказание для конфет введеных вручную
reg.predict([[0, 1, 0, 1, 0, 1, 1, 0, 0, 0.93, 0.635]])

array([[63.33202643]])